# Author: Leah Neukirchen <leah@vuxu.org>

"ui.cursor" = { bg = "yellow", fg = "black" }
"ui.cursor.primary" = { bg = "green", fg = "black" }
"ui.selection" = { fg = "green", modifiers = ["bold"] }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.cursor.match" = { fg = "green" }

# [palette]
# "green" = "#00ff00"
