# https://github.com/dexpota/kitty-themes/blob/c4bee86ce8372d3426620e27086d6afa6873a98c/themes/SeaShells.conf
inherits = "base16-darktooth-better"

ui.background = { "bg" = "selection_background" }

[palette]
base00               = "#08131a" # Default Background
base01               = "#d05023" # Lighter Background (Used for status bars, line number and folding marks)
base02               = "#027b9b" # Selection Background
base03               = "#fba02f" # Comments, Invisibles, Line Highlighting
base04               = "#1d4850" # Dark Foreground (Used for status bars)
base05               = "#68d3f0" # Default Foreground, Caret, Delimiters, Operators
base06               = "#50a3b5" # Light Foreground (Not often used)
base07               = "#deb88d" # Light Background (Not often used)
base08               = "#424b52" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09               = "#d38677" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A               = "#618c98" # Classes, Markup Bold, Search Text Background
base0B               = "#fdd29e" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C               = "#1abcdd" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D               = "#bbe3ee" # Functions, Methods, Attribute IDs, Headings
base0E               = "#86abb3" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0E1              = "#86abb3" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F               = "#fee3cd" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
background           = "#08131a"
foreground           = "#deb88d"
cursor               = "#fba02f"
selection_background = "#1e4862"


# background            #08131a
# foreground            #deb88d
# cursor                #fba02f
# selection_background  #1e4862
# color0                #17384c
# color1                #d05023
# color2                #027b9b
# color3                #fba02f
# color4                #1d4850
# color5                #68d3f0
# color6                #50a3b5
# color7                #deb88d
# color8                #424b52
# color9                #d38677
# color10               #618c98
# color11               #fdd29e
# color12               #1abcdd
# color13               #bbe3ee
# color14               #86abb3
# color15               #fee3cd
# selection_foreground #08131a
