#!/bin/sh

if herbstclient silent get_attr my_polybar_is_hidden ; then
	polybar-msg cmd hide
	herbstclient remove_attr my_polybar_is_hidden
else
	polybar-msg cmd show
	herbstclient new_attr bool my_polybar_is_hidden
fi
