[[colors.indexed_colors]]
color = "0xfe8625"
index = 16

[[colors.indexed_colors]]
color = "0xa87322"
index = 17

[[colors.indexed_colors]]
color = "0x32302f"
index = 18

[[colors.indexed_colors]]
color = "0x504945"
index = 19

[[colors.indexed_colors]]
color = "0x928374"
index = 20

[[colors.indexed_colors]]
color = "0xd5c4a1"
index = 21

[colors.bright]
black = "0x665c54"
blue = "0x0d6678"
cyan = "0x8ba59b"
green = "0x95c085"
magenta = "0x8f4673"
red = "0xfb543f"
white = "0xfdf4c1"
yellow = "0xfac03b"

[colors.cursor]
cursor = "0xa89984"
text = "0x1d2021"

[colors.normal]
black = "0x1d2021"
blue = "0x0d6678"
cyan = "0x8ba59b"
green = "0x95c085"
magenta = "0x8f4673"
red = "0xfb543f"
white = "0xa89984"
yellow = "0xfac03b"

[colors.primary]
background = "0x1d2021"
foreground = "0xa89984"
