[[colors.indexed_colors]]
color = "#fe8625"
index = 16

[[colors.indexed_colors]]
color = "#a87322"
index = 17

[[colors.indexed_colors]]
color = "#32302f"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#928374"
index = 20

[[colors.indexed_colors]]
color = "#d5c4a1"
index = 21

[colors.bright]
black = "#665c54"
blue = "#0d6678"
cyan = "#8ba59b"
green = "#95c085"
magenta = "#8f4673"
red = "#fb543f"
white = "#fdf4c1"
yellow = "#fac03b"

[colors.cursor]
cursor = "#a89984"
text = "#1d2021"

[colors.normal]
black = "#1d2021"
blue = "#0d6678"
cyan = "#8ba59b"
green = "#95c085"
magenta = "#8f4673"
red = "#fb543f"
white = "#a89984"
yellow = "#fac03b"

[colors.primary]
background = "#1d2021"
foreground = "#a89984"
