#!/bin/sh
xinput set-prop 'ELAN1300:00 04F3:3057 Touchpad' 'libinput Tapping Enabled' 1
pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo 10%
./.fehbg
($TERMINAL -e peaclock) &
($TERMINAL -e battery) &
nvim -c 'set norelativenumber|set colorcolumn=0|split /home/bhavya/Documents/todo.md' /home/bhavya/Documents/apps.md
