#!/usr/bin/env /bin/bash

# finds and prints path of random jpg/png/jpeg in your pictures directory
# dependencies: tree

#PICS_DIR="/home/bhavya/pictures"
PICS_DIR="$1"

NUM=$(tree $PICS_DIR -f | grep -e "/.*\.\(jpg\|png\|jpeg\)" -o | wc -l)
RAND=$(( $(( $RANDOM % $NUM )) + 1 ))
PHOTO=$(tree $PICS_DIR -f | grep -e "/.*\.\(jpg\|png\|jpeg\)" -o | sed "${RAND}q;d")
echo $PHOTO
